---
title: "CKForms - Manual for version 2.x"
link-citations: yes
output:
  html_document: default
  pdf_document: default
  word_document: default
bibliography: bibliography.bib
---


## Notation and convention

This instruction descibes the functionality associated with the following article [@BJT2021]


We use the notation of the theory of real Lie algebras from CoReLG Package, [@CoReLG].

## Function for real Lie algebras

```
RealRank(g)
```
The input is a real Lie algebra $\mathfrak{g}$ (as an Lie algebra object). The output is the real rank of $\mathfrak{g}$ (the dimension of the Cartan subalgebra of $\mathfrak{g}$).

```
AHypRank(g)
```
The input is a real Lie algebra $\mathfrak{g}$ (as an Lie algebra object). The output is the a-hyperbolic rank of $\mathfrak{g}$.

Example:

```bash
gap> g:=RealFormById("A",5,6);
<Lie algebra of dimension 35 over SqrtField>
gap> NameRealForm(g);
"sl(6,R)"
gap> RealRank(g);
5
gap> AHypRank(g);
3
```

## Main procedure

As in Theorem 6 in [@BJT2021] we are checking three conditions:

* $L_0$ - Calabi–Markus phenomenon, $\operatorname{rank}_{\mathbb{R}} \mathfrak{g}=\operatorname{rank}_{\mathbb{R}} \mathfrak{h}$
* $L_1$ - $\operatorname{rank}_{\textrm{a-hyp}}(\mathfrak{g}) =\operatorname{rank}_{\textrm{a-hyp}}(\mathfrak{h})$
* $L_2$ - $\operatorname{rank}_{\textrm{a-hyp}}(\mathfrak{g}) >\operatorname{rank}_{\mathbb{R}} \mathfrak{h}$
* $L_3$ - none of the above conditions is met

```bash
gap> CheckRankConditions("A",5,6);
g=sl(6,R) | real rank(g)=5 | a-hyp rank(g)=3
----------------------------
#1: h=sl(3,R)+sl(3,R) + a torus of  1 non-compact dimensions | real rank(h)=5 | ahyp rank(h)=2
 | L0-true | L1-false | L2-false | L3-false
----
#2: h=sl(3,C) + a torus of 1 compact dimensions | real rank(h)=2 | ahyp rank(h)=1
 | L0-false | L1-false | L2-true | L3-false
----
#3: h=sl(2,R)+sl(4,R) + a torus of  1 non-compact dimensions | real rank(h)=5 | ahyp rank(h)=3
 | L0-true | L1-true | L2-false | L3-false
----
#4: h=sl(5,R) + a torus of  1 non-compact dimensions | real rank(h)=5 | ahyp rank(h)=2
 | L0-true | L1-false | L2-false | L3-false
----
#5: h=sl(3,R) | real rank(h)=2 | ahyp rank(h)=1
 | L0-false | L1-false | L2-true | L3-false
----
#6: h=sl(2,R)+sl(3,R) | real rank(h)=3 | ahyp rank(h)=2
 | L0-false | L1-false | L2-false | L3-true
----
#7: h=su(4) | real rank(h)=0 | ahyp rank(h)=0
 | L0-false | L1-false | L2-true | L3-false
----
#8: h=su(2,2) | real rank(h)=2 | ahyp rank(h)=2
 | L0-false | L1-false | L2-true | L3-false
----
#9: h=sl(2,H) | real rank(h)=1 | ahyp rank(h)=1
 | L0-false | L1-false | L2-true | L3-false
----
#10: h=sl(4,R) | real rank(h)=3 | ahyp rank(h)=2
 | L0-false | L1-false | L2-false | L3-true
----
#11: h=sp(3,R) | real rank(h)=3 | ahyp rank(h)=3
 | L0-false | L1-true | L2-false | L3-false
----
```

The next possible `h` are consecutive maximal subalgebras of `g` generated by the function `MaximalReductiveSubalgebras` from [@CoReLG].

All calculations are being done in the "Database - v2" section.

Next if `L3` is equal to `true`, then we check the condition for orbits as in Theorem 5 in [@BJT2021].

```bash
gap> CheckProperSL2RAction("A",5,6,6);
proper
```

The last argument of the function `CheckProperSL2RAction` is an index of the maximal subalgebra (`subalgs` output   `MaximalReductiveSubalgebras`).

## References